digitalocean:
    token:   <enter-your-token-here>
    image:   ubuntu-14-04-x64
    region:  nyc2
    size:    512mb
    ssh_key: ~/.ssh/id_rsa

linode:
    token:        <enter-your-token-here>
    distribution: Ubuntu 14.04 LTS
    datacenter:   newark
    plan:         Linode 1024
    ssh_key:      ~/.ssh/id_rsa
